### ISSUE TITLE
Missing step in documentation?

### ISSUE THREAD

**Issue by chrishepner** [niftylettuce/gulp-aws-splash#1]
Hi! Thanks for sharing this project.

It appears that if you follow the instructions under the [Development](https://github.com/niftylettuce/gulp-aws-splash#development) section of Readme.md exactly, necessary files will not have been written to the /assets/dist/ folder at the time `gulp watch` is run. It appears to be necessary to run `gulp build` beforehand - you may want to update the documentation to reflect this.

**Comment by niftylettuce** [comment]
Fixed, there is a `postinstall` now in `package.json` that takes care of this for you.

**Comment by chrishepner** [comment]
Perfect!
