### ISSUE TITLE
variable @btn-border-radius-base is undefined

### ISSUE THREAD

**Issue by jeromegv** [niftylettuce/gulp-aws-splash#3]
Hi

I got the project using git clone and did not modify anything
Did "npm install" and this is the error I'm getting

Any idea?

[12:03:12] Finished 'bower' after 22 s
[12:03:12] Starting 'font-awesome'...
[12:03:12] Finished 'font-awesome' after 30 ms
[12:03:12] Starting 'less'...

/Users/gagnonje/Dropbox/gulp-aws-splash/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/decorators/unhandledRejection.js:80
		throw e;
		      ^
Error: variable @btn-border-radius-base is undefined in file /Users/gagnonje/Dropbox/gulp-aws-splash/assets/dist/bower/bootstrap/less/buttons.less line no. 20

npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! gulp-aws-splash@0.0.1 postinstall: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gulp-aws-splash@0.0.1 postinstall script 'gulp build'.
npm ERR! This is most likely a problem with the gulp-aws-splash package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build
npm ERR! You can get their info via:
npm ERR!     npm owner ls gulp-aws-splash
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/gagnonje/Dropbox/gulp-aws-splash/npm-debug.log

**Comment by jeromegv** [comment]
Looks like a problem that appeared with bootstrap 3.3.5

My workaround to make it work is to go to bower.json and switch to "bootstrap": "3.3.4", instead of "bootstrap": "~3.3.4",

**Comment by chadfurman** [comment]
Changing to 3.3.4 also fixed this for me
